TAW_HLL_Campaign/Areas/Admin/Controllers/GamesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TAW_HLL_Campaign.Data;
using TAW_HLL_Campaign.Models;

namespace TAW_HLL_Campaign.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class GamesController : Controller
    {
        private readonly CampaignContext _context;
        public GamesController(CampaignContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            // Assuming the Game model has a property called "Status" to represent the game state
            var lastGame = await _context.Games.OrderByDescending(g => g.GameId).FirstOrDefaultAsync();

            if (lastGame != null)
            {
                if (lastGame.Status == Status.Active)
                {
                    // If the last game is active, redirect to another view
                    return RedirectToAction("ActiveGameView");
                }
            }

            // If there's no active game, or if the last game is not active, show the default Index view
            return View();
        }
        // GET: Admin/Game/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Games/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GameID,Name,Status")] Game game)
        {
            
            return View(game);
        }
    }
}

TAW_HLL_Campaign/Areas/Admin/Controllers/RoadsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TAW_HLL_Campaign.Data;
using TAW_HLL_Campaign.Models;

namespace TAW_HLL_Campaign.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RoadsController : Controller
    {
        private readonly CampaignContext _context;

        public RoadsController(CampaignContext context)
        {
            _context = context;
        }

        // GET: Admin/Roads
        public async Task<IActionResult> Index()
        {
              return _context.Roads != null ? 
                          View(await _context.Roads.ToListAsync()) :
                          Problem("Entity set 'CampaignContext.Roads'  is null.");
        }

        // GET: Admin/Roads/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Roads == null)
            {
                return NotFound();
            }

            var road = await _context.Roads
                .FirstOrDefaultAsync(m => m.RoadID == id);
            if (road == null)
            {
                return NotFound();
            }

            return View(road);
        }

        // GET: Admin/Roads/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Roads/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RoadID,Name,StartSectorID,EndSectorID")] Road road)
        {
            if (ModelState.IsValid)
            {
                _context.Add(road);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(road);
        }

        // GET: Admin/Roads/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Roads == null)
            {
                return NotFound();
            }

            var road = await _context.Roads.FindAsync(id);
            if (road == null)
            {
                return NotFound();
            }
            return View(road);
        }

        // POST: Admin/Roads/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RoadID,Name,StartSectorID,EndSectorID")] Road road)
        {
            if (id != road.RoadID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(road);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoadExists(road.RoadID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(road);
        }

        // GET: Admin/Roads/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Roads == null)
            {
                return NotFound();
            }

            var road = await _context.Roads
                .FirstOrDefaultAsync(m => m.RoadID == id);
            if (road == null)
            {
                return NotFound();
            }

            return View(road);
        }

        // POST: Admin/Roads/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Roads == null)
            {
                return Problem("Entity set 'CampaignContext.Roads'  is null.");
            }
            var road = await _context.Roads.FindAsync(id);
            if (road != null)
            {
                _context.Roads.Remove(road);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoadExists(int id)
        {
          return (_context.Roads?.Any(e => e.RoadID == id)).GetValueOrDefault();
        }
    }
}

TAW_HLL_Campaign/Areas/Admin/Controllers/TeamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TAW_HLL_Campaign.Data;
using TAW_HLL_Campaign.Models;

namespace TAW_HLL_Campaign.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TeamsController : Controller
    {
        private readonly CampaignContext _context;

        public TeamsController(CampaignContext context)
        {
            _context = context;
        }

        // GET: Admin/Teams
        public async Task<IActionResult> Index()
        {
              return _context.Teams != null ? 
                          View(await _context.Teams.Include(t => t.Stockpile).ToListAsync()) :
                          Problem("Entity set 'CampaignContext.Teams'  is null.");
        }

        // GET: Admin/Teams/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Teams == null)
            {
                return NotFound();
            }

            var team = await _context.Teams
                .Include(t => t.Stockpile)
                .FirstOrDefaultAsync(m => m.TeamID == id);
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }

        // GET: Admin/Teams/Create
        public IActionResult Create()
        {
            var teamCount = _context.Teams.Count();

            if (teamCount < 2)
            {
                return View();
            }
            else
            {
                // Return a view or message indicating that the maximum team limit has been reached.
                return View("MaxTeamLimitReached");
            }
        }

        // POST: Admin/Teams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TeamID,Name,Nation")] Team team)
        {
            if (ModelState.IsValid)
            {
                var teamCount = _context.Teams.Count();

                if (teamCount < 2)
                {
                    // Create a new Stockpile
                    var stockpile = new Stockpile();

                // Associate the Stockpile with the Team
                team.Stockpile = stockpile;

                // Add the Team and Stockpile to the context
                _context.Add(team);
                _context.Add(stockpile);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
                }
            }
            else
            {
                // Return a view or message indicating that the maximum team limit has been reached.
                return View("MaxTeamLimitReached");
            }
            return View(team);
        }

        // GET: Admin/Teams/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Teams == null)
            {
                return NotFound();
            }

            var team = await _context.Teams.FindAsync(id);
            if (team == null)
            {
                return NotFound();
            }
            return View(team);
        }

        // POST: Admin/Teams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TeamID,Name,Nation")] Team team)
        {
            if (id != team.TeamID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(team);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeamExists(team.TeamID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(team);
        }

        // GET: Admin/Teams/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Teams == null)
            {
                return NotFound();
            }

            var team = await _context.Teams
                .FirstOrDefaultAsync(m => m.TeamID == id);
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }

        // POST: Admin/Teams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Teams == null)
            {
                return Problem("Entity set 'CampaignContext.Teams'  is null.");
            }
            var team = await _context.Teams.FindAsync(id);
            if (team != null)
            {
                // Remove the associated Stockpile
                var stockpile = team.Stockpile;
                if (stockpile != null)
                {
                    _context.Stockpiles.Remove(stockpile);
                }

                // Find and update the associated sectors to set TeamID to null
                var sectors = await _context.Sectors
                    .Where(s => s.TeamID == id)
                    .ToListAsync();

                foreach (var sector in sectors)
                {
                    sector.TeamID = null;
                    _context.Update(sector);
                }

                _context.Teams.Remove(team);
                
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TeamExists(int id)
        {
          return (_context.Teams?.Any(e => e.TeamID == id)).GetValueOrDefault();
        }
    }
}

TAW_HLL_Campaign/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TAW_HLL_Campaign</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TAW_HLL_Campaign.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TAW_HLL_Campaign</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Maintain" asp-action="Index">Admin</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TAW_HLL_Campaign - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TAW_HLL_Campaign/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TAW_HLL_Campaign</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TAW_HLL_Campaign.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TAW_HLL_Campaign</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Games" asp-action="Index">Game</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Calculator" asp-action="Index">Calculator</a>
                        </li>                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Teams" asp-action="Index">Teams</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Sectors" asp-action="Index">Sectors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Roads" asp-action="Index">Roads</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="BuildingTypes" asp-action="Index">BuildingTypes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Building" asp-action="Index">Buildings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Maneuvers" asp-action="Index">Maneuvers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Defences" asp-action="Index">Defences</a>
                        </li>
                        
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TAW_HLL_Campaign - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>